# IMPORTING THE LIBRARIES

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# READING THE DATAFRAMES

In [21]:
df=pd.read_csv(r'C:\Users\LENOVO\OneDrive\Desktop\DATASETS DOWNLOAD\archive (5)\dataset.csv',header=0)
df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [22]:
print(df.shape)

(4920, 18)


In [23]:
df1=pd.read_csv(r'C:\Users\LENOVO\OneDrive\Desktop\DATASETS DOWNLOAD\archive (5)\Symptom-severity.csv',header=0)
df1.head()

Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5

In [24]:
print(df1.shape)

(133, 2)


In [25]:
print(df.isnull().sum())

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64


# PRE PROCESSING

In [26]:
df.isna().sum()
df.isnull().sum()

cols = df.columns
data = df[cols].values.flatten()

s = pd.Series(data)
s = s.str.strip()
s = s.values.reshape(df.shape)

df = pd.DataFrame(s, columns=df.columns)

df = df.fillna(0)
df.head()

Disease  Symptom_1             Symptom_2             Symptom_3  \
0  Fungal infection    itching             skin_rash  nodal_skin_eruptions   
1  Fungal infection  skin_rash  nodal_skin_eruptions   dischromic _patches   
2  Fungal infection    itching  nodal_skin_eruptions   dischromic _patches   
3  Fungal infection    itching             skin_rash   dischromic _patches   
4  Fungal infection    itching             skin_rash  nodal_skin_eruptions   

             Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0  dischromic _patches         0         0         0         0         0   
1                    0         0         0         0         0         0   
2                    0         0         0         0         0         0   
3                    0         0         0         0         0         0   
4                    0         0         0         0         0         0   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

  Symptom_16 Symptom_17  
0          0          0  
1          0          0  
2          0          0  
3          0          0  
4          0          0

In [27]:
print(df.isnull().sum())

Disease       0
Symptom_1     0
Symptom_2     0
Symptom_3     0
Symptom_4     0
Symptom_5     0
Symptom_6     0
Symptom_7     0
Symptom_8     0
Symptom_9     0
Symptom_10    0
Symptom_11    0
Symptom_12    0
Symptom_13    0
Symptom_14    0
Symptom_15    0
Symptom_16    0
Symptom_17    0
dtype: int64


In [28]:
print(df1.isnull().sum())

Symptom    0
weight     0
dtype: int64


In [29]:
vals = df.values
vals

array([['Fungal infection', 'itching', 'skin_rash', ..., 0, 0, 0],
       ['Fungal infection', 'skin_rash', 'nodal_skin_eruptions', ..., 0,
        0, 0],
       ['Fungal infection', 'itching', 'nodal_skin_eruptions', ..., 0, 0,
        0],
       ...,
       ['Urinary tract infection', 'burning_micturition',
        'bladder_discomfort', ..., 0, 0, 0],
       ['Psoriasis', 'skin_rash', 'joint_pain', ..., 0, 0, 0],
       ['Impetigo', 'skin_rash', 'high_fever', ..., 0, 0, 0]],
      dtype=object)

In [30]:
symptoms = df1['Symptom'].unique()
symptoms

array(['itching', 'skin_rash', 'nodal_skin_eruptions',
       'continuous_sneezing', 'shivering', 'chills', 'joint_pain',
       'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting',
       'vomiting', 'burning_micturition', 'spotting_urination', 'fatigue',
       'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings',
       'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat',
       'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes',
       'breathlessness', 'sweating', 'dehydration', 'indigestion',
       'headache', 'yellowish_skin', 'dark_urine', 'nausea',
       'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain',
       'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever',
       'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure',
       'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes',
       'malaise', 'blurred_and_distorted_vision', 'phlegm',
       'throat_irritation', 'redness_of_eyes', 'sinus_pressu

In [31]:
for i in range(len(symptoms)):
    vals[vals == symptoms[i]] = df1[df1['Symptom'] == symptoms[i]]['weight'].values[0]
    
d = pd.DataFrame(vals, columns=cols)
d.head()

Disease Symptom_1 Symptom_2            Symptom_3  \
0  Fungal infection         1         3                    4   
1  Fungal infection         3         4  dischromic _patches   
2  Fungal infection         1         4  dischromic _patches   
3  Fungal infection         1         3  dischromic _patches   
4  Fungal infection         1         3                    4   

             Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0  dischromic _patches         0         0         0         0         0   
1                    0         0         0         0         0         0   
2                    0         0         0         0         0         0   
3                    0         0         0         0         0         0   
4                    0         0         0         0         0         0   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

  Symptom_16 Symptom_17  
0          0          0  
1          0          0  
2          0          0  
3          0          0  
4          0          0

In [32]:
d = d.replace('dischromic _patches', 0)
d = d.replace('spotting_ urination',0)
df = d.replace('foul_smell_of urine',0)
df.head()

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  \
0  Fungal infection          1          3          4          0          0   
1  Fungal infection          3          4          0          0          0   
2  Fungal infection          1          4          0          0          0   
3  Fungal infection          1          3          0          0          0   
4  Fungal infection          1          3          4          0          0   

   Symptom_6  Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  \
0          0          0          0          0           0           0   
1          0          0          0          0           0           0   
2          0          0          0          0           0           0   
3          0          0          0          0           0           0   
4          0          0          0          0           0           0   

   Symptom_12  Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0           0           0           0           0           0           0  
1           0           0           0           0           0           0  
2           0           0           0           0           0           0  
3           0           0           0           0           0           0  
4           0           0           0           0           0           0

In [33]:
(df[cols] == 0).all()  ## GETTING COLOUMNS WITH 0 AS A ENTITY


df['Disease'].value_counts() ## GETTING VALUE COUNTS OF ALL DISEASE

df['Disease'].unique()  ## GETTING ALL THE DISEASE

data = df.iloc[:,1:].values  # storing all the weights of symptoms as data


labels = df['Disease'].values #storing disease as labels

# TRAIN TEST SPLIT

In [34]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, labels, shuffle=True, train_size = 0.85)
#print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)




# MODEL BUILDING

In [35]:
from sklearn.svm import SVC

model = SVC()
model.fit(x_train, y_train)

preds = model.predict(x_test)
print(preds)

['Dimorphic hemmorhoids(piles)' 'Hepatitis E' 'Drug Reaction' 'GERD'
 '(vertigo) Paroymsal  Positional Vertigo' 'Fungal infection'
 'Osteoarthristis' 'Varicose veins' 'Migraine' 'Hepatitis E'
 'Osteoarthristis' 'GERD' 'Arthritis' 'GERD' 'Hypothyroidism' 'Malaria'
 'Hepatitis E' 'Hyperthyroidism' 'Jaundice' 'Hypertension' 'Psoriasis'
 'Alcoholic hepatitis' 'Hepatitis E' 'Pneumonia' 'Fungal infection'
 '(vertigo) Paroymsal  Positional Vertigo' 'Dengue' 'AIDS' 'Common Cold'
 'Hyperthyroidism' 'hepatitis A' 'hepatitis A' 'Gastroenteritis'
 'Chicken pox' 'Hyperthyroidism' 'Tuberculosis' 'Migraine' 'Malaria'
 'Varicose veins' 'Paralysis (brain hemorrhage)' 'hepatitis A'
 'Bronchial Asthma' 'Bronchial Asthma' 'hepatitis A' 'Dengue'
 'Osteoarthristis' 'Hepatitis B' 'GERD' 'Jaundice' 'Impetigo'
 'Hepatitis D' 'Cervical spondylosis' 'Hypertension' 'Chronic cholestasis'
 'Bronchial Asthma' 'Malaria' 'Jaundice' 'Psoriasis'
 'Cervical spondylosis' 'Common Cold' 'Tuberculosis' 'Malaria' 'Migraine'
 

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,preds)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,preds))

acc=accuracy_score(y_test,preds)
print('accuracy of the model: ',acc)

[[18  0  0 ...  0  0  0]
 [ 0 18  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 11  0  0]
 [ 0  0  0 ...  0 17  0]
 [ 0  0  0 ...  0  0 19]]
classification report: 
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       0.90      0.90      0.90        20
                                   AIDS       1.00      1.00      1.00        18
                                   Acne       1.00      1.00      1.00        12
                    Alcoholic hepatitis       0.92      0.73      0.81        15
                                Allergy       0.85      0.73      0.79        15
                              Arthritis       0.89      1.00      0.94        17
                       Bronchial Asthma       0.93      0.74      0.82        19
                   Cervical spondylosis       1.00      0.84      0.91        19
                            Chicken pox       1.00      1.00      1.00        17
         

# DEPLOYMENT

# DEPLOYING ONLY FOR GERD AND HEPATITIS C

In [37]:
from tkinter import *
from tkinter import messagebox
import sys 
import urllib
import urllib.request

In [38]:
def message():
    if (Symptom1.get() == "None" and  Symptom2.get() == "None" and Symptom3.get() == "None" and Symptom4.get() == "None" and Symptom5.get() == "None"):
        messagebox.showinfo("OPPS!!", "ENTER  SYMPTOMS PLEASE")
    else :
        SVM()

def SVM():
    psymptoms = [Symptom1.get(),Symptom2.get(),Symptom3.get(),Symptom4.get(),Symptom5.get()]
    loc = location.get()
    a = np.array(df1["Symptom"])
    b = np.array(df1["weight"])
    for j in range(len(psymptoms)):
        for k in range(len(a)):
            if psymptoms[j]==a[k]:
                psymptoms[j]=b[k]
    nulls = [0,0,0,0,0,0,0,0,0,0,0,0]
    psy = [psymptoms + nulls]

    pred2 = model.predict(psy)
    t3.delete("1.0", END)
    t3.insert(END, pred2[0])

    if(pred2[0]=="GERD"):
        z=urllib.request.urlopen('https://api.thingspeak.com/update?api_key=NXYP6B135Z91RK7Z&field1='+str(loc))
        z.read()
    if(pred2[0]=="Hepatitis C"):
        r=urllib.request.urlopen('https://api.thingspeak.com/update?api_key=NXYP6B135Z91RK7Z&field1='+str(loc))
        r.read()

In [39]:
root = Tk()  ## it creates a gui window
root.title(" Disease Prediction From Symptoms") ## assigning title
root.configure()

Symptom1 = StringVar()
Symptom1.set(None)
Symptom2 = StringVar()
Symptom2.set(None)
Symptom3 = StringVar()
Symptom3.set(None)
Symptom4 = StringVar()
Symptom4.set(None)
Symptom5 = StringVar()
Symptom5.set(None)
location = StringVar()
location.set(None)

w2 = Label(root, justify=CENTER, text=" Disease Prediction From Symptoms ")
w2.config(font=("Helvetica", 30))
w2.grid(row=1, column=0, columnspan=2, padx=100)
NameLb1 = Label(root, text="")
NameLb1.config(font=("Helvetica", 20))
NameLb1.grid(row=5, column=1, pady=10,  sticky=W)

S1Lb = Label(root,  text="Symptom 1")
S1Lb.config(font=("Helvetica", 15))
S1Lb.grid(row=7, column=1, pady=10 , sticky=W)

S2Lb = Label(root,  text="Symptom 2")
S2Lb.config(font=("Helvetica", 15))
S2Lb.grid(row=8, column=1, pady=10, sticky=W)

S3Lb = Label(root,  text="Symptom 3")
S3Lb.config(font=("Helvetica", 15))
S3Lb.grid(row=9, column=1, pady=10, sticky=W)

S4Lb = Label(root,  text="Symptom 4")
S4Lb.config(font=("Helvetica", 15))
S4Lb.grid(row=10, column=1, pady=10, sticky=W)

S5Lb = Label(root,  text="Symptom 5")
S5Lb.config(font=("Helvetica", 15))
S5Lb.grid(row=11, column=1, pady=10, sticky=W)

locLb = Label(root,  text="Location")
locLb.config(font=("Helvetica", 15))
locLb.grid(row=12, column=1, pady=10, sticky=W)

lr = Button(root, text="Predict",height=2, width=20, command=message)
lr.config(font=("Helvetica", 15))
lr.grid(row=15, column=1,pady=10)
S4Lb.grid(row=10, column=1, pady=10, sticky=W)

S5Lb = Label(root,  text="Symptom 5")
S5Lb.config(font=("Helvetica", 15))
S5Lb.grid(row=11, column=1, pady=10, sticky=W)

locLb = Label(root,  text="Location")
locLb.config(font=("Helvetica", 15))
locLb.grid(row=12, column=1, pady=10, sticky=W)

lr = Button(root, text="Predict",height=2, width=20, command=message)
lr.config(font=("Helvetica", 15))
lr.grid(row=15, column=1,pady=10)
#OPTIONS = sorted(symptoms)
OPTIONS = ["fatigue", "yellowish_skin", "loss_of_appetite", "yellowing_of_eyes", 'family_history',"stomach_pain", "ulcers_on_tongue", "vomiting", "cough", "chest_pain"]
LOCATIONS = ["New Delhi", "Mumbai", "Chennai", "Kolkata", "Bengaluru"]

S1En = OptionMenu(root, Symptom1,*OPTIONS)
S1En.grid(row=7, column=1)

S2En = OptionMenu(root, Symptom2,*OPTIONS)
S2En.grid(row=8, column=1)

S3En = OptionMenu(root, Symptom3,*OPTIONS)
S3En.grid(row=9, column=1)

S4En = OptionMenu(root, Symptom4,*OPTIONS)
S4En.grid(row=10, column=1)

S5En = OptionMenu(root, Symptom5,*OPTIONS)
S5En.grid(row=11, column=1)

LocEn = OptionMenu(root, location,*LOCATIONS)
LocEn.grid(row=12, column=1)

NameLb = Label(root, text="")
NameLb.config(font=("Helvetica", 20))
NameLb.grid(row=13, column=1, pady=10,  sticky=W)
t3 = Text(root, height=2, width=20)
t3.config(font=("Helvetica", 20))
t3.grid(row=19, column=1 , padx=10)

root.mainloop()